config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :dishes, except: [:update, :destroy] do
    resources :items, only: :create
  end
  resources :products, only: [:index, :create]
  resources :units, only: [:index, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :items
  validates :name, presence: true
  validates :base_servings, numericality: { only_integer: true, greater_than: 0 }
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :unit
  belongs_to :product
  belongs_to :dish, optional: true
  validates :quantity, numericality: { greater_than: 0 }

  # Would it be better to use a helper here?
  def to_s
    "#{quantity} #{unit.name} #{product.name}"
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  scope :a_to_z, -> { order(:name) }
end

app/models/unit.rb
class Unit < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  scope :a_to_z, -> { order(:name) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def index
    @dishes = Dish.all
  end

  def show
    @dish = Dish.find(params[:id])
  end

  def new
    @dish = Dish.new
  end

  def edit
    @dish = Dish.find(params[:id])
  end

  def create
    @dish = Dish.new(dish_params)
    if @dish.save
      flash[:notice] = "New dish (#{@dish.name}) successfully created"
      redirect_to dish_url(@dish)
    else
      render js: "alert('Could not create new dish called #{@dish.name}. #{@dish.errors.full_messages.join('. ')}.')", status: :bad_request
    end
  end

private
  def dish_params
    params.require(:dish).permit(:base_servings, :name, :recipe, :recipe_url)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @dish = Dish.find(params[:dish_id])
    @item = @dish.items.build(item_params)
    if @item.save
      flash[:notice] = "New item (#{@item.to_s}) added to dish"
      redirect_back fallback_location: dish_url(@dish)
    else
      render js: "alert('Could not create new item. #{@item.errors.full_messages.join('. ')}.')", status: :bad_request
    end
  end

private
 def item_params
   params.require(:item).permit(:product_id, :quantity, :unit_id)
 end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # Conventional order of actions: index, show, new, edit, create, update and destroy
  def index
    @products = Product.a_to_z
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "New product (#{@product.name}) successfully created"
    else
      flash[:warning] = "Could not create new product called #{@product.name}. #{@product.errors.full_messages.join('. ')}."
    end
    redirect_to products_url
  end

private
  def product_params
    params.require(:product).permit(:name)
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def index
    @units = Unit.a_to_z
  end

  def create
    @unit = Unit.new(unit_params)
    if @unit.save
      flash[:notice] = "New unit (#{@unit.name}) successfully created"
    else
      flash[:warning] = "Could not create new unit called #{@unit.name}. #{@unit.errors.full_messages.join('. ')}."
    end
    redirect_to units_url
  end

private
  def unit_params
    params.require(:unit).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/dishes/edit.html.erb
<%= link_to "Home", root_path %>

<% if flash[:notice] %>
  <p>
    <%= flash[:notice] %>
  </p>
<% end %>

<h1>
  <%= link_to @dish.name, dish_path(@dish) %>
</h1>
<p>Serves <%= @dish.base_servings %></p>

<h2>
  <% if @dish.recipe_url.present? %>
    <%= link_to "Recipe", @dish.recipe_url %>
  <% else %>
    Recipe
  <% end %>
</h2>

<% if @dish.recipe.present? %>
  <p><%= @dish.recipe %></p>
<% end %>

<h2>
  Ingredients
</h2>
<ol>
  <% @dish.items.each do |item| %>
    <li>
      <%= item.to_s %>
    </li>
  <% end %>
</ol>

<h3>Add a new ingredient</h3>
<%= form_with(model: [@dish, @dish.items.build]) do |form| %>
  <div>
    <%= form.label :quantity %>
    <%= form.number_field :quantity, min: 0,required: true, step: :any %>
  </div>
  <div>
    <%= form.label :unit %>
    <%= form.collection_select :unit_id, Unit.a_to_z, :id, :name, prompt: true %>
  </div>
  <div>
    <%= form.label :product %>
    <%= form.collection_select :product_id, Product.a_to_z, :id, :name, prompt: true %>
  </div>
  <%= form.button %>
<% end %>

app/views/dishes/index.html.erb
<%= link_to "Home", root_path %>
<h1>Dishes</h1>
<%= link_to "Create a new dish", new_dish_path %>
<ol>
  <% @dishes.each do |dish| %>
    <li>
      <%= link_to dish.name, dish_path(dish) %>
    </li>
  <% end %>
</ol>

app/views/dishes/new.html.erb
<%= link_to "Home", root_path %>
<h1>Add a new dish</h1>
<%= form_with model: @dish, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>
  <div>
    <%= form.label :base_servings, "Serves" %>
    <!-- TODO: add min: 1 to prevent errors -->
    <%= form.number_field :base_servings, required: true %>
  </div>
  <div>
    <%= form.label :recipe_url, "Recipe link" %>
    <%= form.url_field :recipe_url %>
  </div>
  <div>
    <%= form.label :recipe %>
    <%= form.text_area :recipe %>
  </div>
  <%= form.button %>
<% end %>
<% if @dish.errors.any? %>
  <p>Could not create dish</p>
  <ul>
    <% @dish.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/dishes/show.html.erb
<%= link_to "Home", root_path %>
<%= link_to "Edit", edit_dish_path(@dish) %>

<% if flash[:notice] %>
  <p>
    <%= flash[:notice] %>
  </p>
<% end %>

<h1><%= @dish.name %></h1>
<p>Serves <%= @dish.base_servings %></p>

<h2>
  <% if @dish.recipe_url.present? %>
    <%= link_to "Recipe", @dish.recipe_url %>
  <% else %>
    Recipe
  <% end %>
</h2>

<% if @dish.recipe.present? %>
  <p><%= @dish.recipe %></p>
<% end %>

<h2>
  Ingredients
</h2>
<ol>
  <% @dish.items.each do |item| %>
    <li>
      <%= item.to_s %>
    </li>
  <% end %>
</ol>

app/views/home/index.html.erb
<h1>Dinder</h1>
<ul>
  <li>
    <%= link_to "Products", products_path %>
  </li>
  <li>
    <%= link_to "Units", units_path %>
  </li>
  <li>
    <%= link_to "Dishes", dishes_path %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dinder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<%= link_to "Home", root_path %>
<div class="flex-container">
  <div class="margin-right">
    <h1>Products</h1>
    <ol>
      <% @products.each do |product| %>
        <li><%= product.name %></li>
      <% end %>
    </ol>
  </div>
  <div>
    <h1>Add a new product</h1>
    <%= form_with model: Product.new do |form| %>
      <%= form.label :name %>
      <%= form.text_field :name, required: true %>
      <%= form.button %>
    <% end %>
    <% if flash[:notice] %>
      <p>
        <%= flash[:notice] %>
      </p>
    <% end %>
    <% if flash[:warning] %>
      <p>
        <%= flash[:warning] %>
      </p>
    <% end %>
  </div>
</div>

app/views/units/index.html.erb
<%= link_to "Home", root_path %>
<div class="flex-container">
  <div class="margin-right">
    <h1>Units</h1>
    <ol>
      <% @units.each do |unit| %>
        <li><%= unit.name %></li>
      <% end %>
    </ol>
  </div>
  <div>
    <h1>Add a new unit</h1>
    <%= form_with model: Unit.new do |form| %>
      <%= form.label :name %>
      <%= form.text_field :name, required: true %>
      <%= form.button %>
    <% end %>
    <% if flash[:notice] %>
      <p>
        <%= flash[:notice] %>
      </p>
    <% end %>
    <% if flash[:warning] %>
      <p>
        <%= flash[:warning] %>
      </p>
    <% end %>
  </div>
</div>